service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dynamodb-local

custom:
  tableName: 'notes-table-${self:provider.stage}'
  wsgi:
    app: api.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["NotesDynamoDBTable", "Arn" ] }
  environment:
    NOTES_TABLE: ${self:custom.tableName}

functions:
  streamStatus:
    handler: wsgi.handler
    events:
      - http:
          path: streamstatus
          method: get
          cors: true
      - http:
          path: note
          method: post
          cors: true
      - http:
          path: note/{proxy+}
          method: get
          cors: true
      - http:
          path: notes/{proxy+}
          method: put
          cors: true
      - http:
          path: notes
          method: get
          cors: true

resources:
  Resources:
    NotesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: noteId
            AttributeType: S
        KeySchema:
          -
            AttributeName: noteId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
