service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: api.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  # app:
  #   handler: wsgi.handler
  #   events:
  #     - http: ANY /
  #     - http: 'ANY {proxy+}'
    # cors:
    #   enabled: true
    #   origin: '*'
  streamStatus:
    handler: wsgi.handler
    events:
      - http:
          path: streamstatus
          method: get
          cors: true
    # cors:
    #   enabled: true
    #   origin: '*'
